# config/meta.yml

meta_product_name: "CoachMe"
meta_title: "CoachMe - Le Sport sans les Porcs!"
meta_description: "L'application numéro une pour trouver le meilleur coach sportif près de chez vous!"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
